tme4: Banque.cpp Compte.cpp main.cpp
	g++ -std=c++1y -O0 -g3 -Wall -c -lpthread -o ./Compte.o ./Compte.cpp
	g++ -std=c++1y -O0 -g3 -Wall -c -lpthread -o ./Banque.o ./Banque.cpp
	g++ -std=c++1y -O0 -g3 -Wall -c -lpthread -o ./tme4.o ./main.cpp
	g++ -lpthread -o ./tme4 ./Compte.o ./Banque.o ./tme4.o
